export const products = [
    {
      id: 1,
      title: "Tomato",
      description: " ",
      price: "25",
      img: "https://as1.ftcdn.net/v2/jpg/02/69/81/22/1000_F_269812294_BoetDGDa1eGotgv3t5DjRKWbNKCKqZ5r.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 2,
      title: "carrot",
      description: " ",
      price: "20",
      img: "https://i.pinimg.com/564x/a7/49/87/a74987d160e204e4120ad87c1b683dbd.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 3,
      title: "Potato",
      description: " ",
      price: "30",
      img: "https://t3.ftcdn.net/jpg/00/41/30/10/360_F_41301053_AbLi3hlosbLajBo7lQdNyfGz9eusxY1x.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Red chill",
      description: "",
      price: "10",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3c0rxp4WXD6NPsrefMInybeSOVQlR6pYmeg&usqp=CAU",
      quantity: 1,
    },
    {
      id: 5,
      title: "Onion",
      description: " ",
      price: "40",
      img: "https://static9.depositphotos.com/1380093/1092/v/600/depositphotos_10929781-stock-illustration-onions.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 6,
      title: "Sweet corn",
      description: " ",
      price: "60",
      img: "https://thumbs.dreamstime.com/z/double-sweet-corn-ears-isolated-white-background-as-package-design-element-107015740.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 7,
      title: "Brinjal",
      description: " ",
      price: "25",
      img: "https://c8.alamy.com/comp/EW9FDT/vector-illustration-of-fresh-organic-brinjal-EW9FDT.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 8,
      title: "wheat",
      description: "Best mobile ever",
      price: "10",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFk10crqpAidOUW2hdNimvsGlU1cye3oszUA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 9,
      title: "cabbage",
      description: " ",
      price: "24",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkzd2M6zi7Jb2RxHQBe4y20125vhMjDfI-zg&usqp=CAU?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
  ];